# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ptp4r}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Atwood"]
  s.date = %q{2009-12-28}
  s.description = %q{Ruby library exposing libptp (picture taking protocol)}
  s.email = %q{catwood@gmail.com}
  s.extensions = ["ext/ptp4r_ext/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "ext/ptp4r_ext/extconf.rb",
     "ext/ptp4r_ext/libptp-endian.h",
     "ext/ptp4r_ext/myusb.c",
     "ext/ptp4r_ext/properties.c",
     "ext/ptp4r_ext/ptp-pack.h",
     "ext/ptp4r_ext/ptp.c",
     "ext/ptp4r_ext/ptp.h",
     "ext/ptp4r_ext/ptp4r_ext.c",
     "ext/ptp4r_ext/ptpcam.c",
     "ext/ptp4r_ext/ptpcam.h",
     "lib/ptp4r.rb",
     "lib/ptp4r/camera.rb",
     "lib/ptp4r/image.rb",
     "lib/ptp4r_ext.bundle",
     "test/helper.rb",
     "test/test_ptp4r.rb"
  ]
  s.homepage = %q{http://github.com/catwood/ptp4r}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["ext"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruby library of libptp}
  s.test_files = [
    "test/helper.rb",
     "test/test_ptp4r.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

